'use client';

import React, { useState } from 'react';
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import interactionPlugin from '@fullcalendar/interaction';
import { EmployeeLaborEvent } from '@/types/laborEvent';
import { useModal } from '@/hooks/useModal';
import useEmployeeList from '@/hooks/useEmployeeList';
import '@/styles/calendar.css';
import {
  EyeIcon,
  PencilIcon,
  TrashIcon
} from '@heroicons/react/24/outline';

interface Props {
  onEventClick?: (event: EmployeeLaborEvent) => void;
  onDateSelect?: (start: Date, end: Date) => void;
  // New props to receive events and control functions from parent hook
  events: EmployeeLaborEvent[];
  isLoading: boolean;
  refreshEvents: () => Promise<void>;
  deleteAssignment: (id: number) => Promise<void>;
}

const LaborEventsCalendar: React.FC<Props> = ({ onEventClick, onDateSelect, events, isLoading, refreshEvents, deleteAssignment }) => {
  const { employees } = useEmployeeList();
  const { showError } = useModal();
  const [anchor, setAnchor] = useState<{ x: number; y: number } | null>(null);
  const [selectedEvent, setSelectedEvent] = useState<EmployeeLaborEvent | null>(null);
  const menuOpenedAtRef = React.useRef<number | null>(null);
  const [calendarKey, setCalendarKey] = useState(0); // Force re-render key

  // Force calendar re-render when events change
  React.useEffect(() => {
    setCalendarKey(prev => prev + 1);
  }, [events]);

  // Also force re-render when employees change (needed for event titles)
  React.useEffect(() => {
    setCalendarKey(prev => prev + 1);
  }, [employees]);

  // Función auxiliar para determinar el color del evento según su estado
  const getEventColor = (status: string) => {
    switch (status) {
      case 'active':
        return '#3B4D36'; // Verde oscuro
      case 'completed':
        return '#6F7153'; // Verde grisáceo
      case 'cancelled':
        return '#E7DCC1'; // Beige
      default:
        return '#A7AA94'; // Verde claro
    }
  };

  // Convertir eventos a formato FullCalendar
  const calendarEvents = events.map(event => {
    const emp = employees.find(e => String(e.id) === String(event.employee_id || (event as any).employee_labor_event_employee_id));
    const employeeName = emp ? emp.name : 'Empleado';
    const titleName = (event as any).labor_event_name || `Evento #${event.labor_event_id}`;

    return {
      id: String(event.id),
      title: `${titleName} - ${employeeName}`,
      start: event.start_date,
      end: event.end_date || undefined,
      backgroundColor: '#A7AA94',
      borderColor: '#6F7153',
      textColor: '#3B4D36',
      extendedProps: { ...event }
    };
  });

  const openMenuForEvent = (ev: any, clientX: number, clientY: number) => {
    const eventObj = events.find(e => String(e.id) === String(ev.id));
    setSelectedEvent(eventObj || null);
    setAnchor({ x: clientX, y: clientY });
    // mark when menu was opened to avoid immediate outside-click closing
    menuOpenedAtRef.current = Date.now();
  };

  const closeMenu = () => {
    setAnchor(null);
    setSelectedEvent(null);
    menuOpenedAtRef.current = null;
  };

  const handleDeleteClick = async () => {
    if (!selectedEvent) return;
    try {
      await deleteAssignment(selectedEvent.id);
      // Force refresh of calendar events after deletion
      await refreshEvents();
      closeMenu();
    } catch (err) {
      showError('Error', 'No se pudo eliminar la asignación');
    }
  };

  const handleEventClick = (info: any) => {
    // Prevent the browser context menu and ignore right-clicks
    const jsEvent = info.jsEvent;
    if (jsEvent) {
      // Prevent default to stop browser context menu appearing
      jsEvent.preventDefault();
      jsEvent.stopPropagation();
      // If right-click (button === 2) don't open the custom menu
      if (jsEvent.button === 2) return;
    }

    const event = events.find(e => String(e.id) === info.event.id);
    if (event && onEventClick) {
      onEventClick(event);
    }
    // open the small options menu near cursor (offset a little)
    const { clientX = 0, clientY = 0 } = jsEvent || {};
    openMenuForEvent(info.event.toPlainObject(), clientX + 6, clientY + 6);
  };

  // Close menu on outside click
  React.useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (!anchor) return;
      // ignore clicks that happen immediately after opening the menu (often generated by the same interaction)
      if (menuOpenedAtRef.current && Date.now() - menuOpenedAtRef.current < 300) return;
      // If click is outside the menu, close it
      const target = e.target as HTMLElement | null;
      if (!target) return;
      const menu = document.querySelector('.laborevent-options-menu');
      if (menu && !menu.contains(target)) {
        closeMenu();
      }
    };
    document.addEventListener('click', handler);
    return () => document.removeEventListener('click', handler);
  }, [anchor]);

  const handleDateSelect = (selectInfo: any) => {
    if (onDateSelect) {
      onDateSelect(selectInfo.start, selectInfo.end);
    }
  };

  if (isLoading) {
    return <div className="flex items-center justify-center h-96">Cargando eventos...</div>;
  }

  return (
    <div className="calendar-container bg-white rounded-lg shadow p-4">
      <FullCalendar
        key={calendarKey} // Force re-render when events change
        plugins={[dayGridPlugin, timeGridPlugin, interactionPlugin]}
        initialView="dayGridMonth"
        headerToolbar={{
          left: 'prev,next today',
          center: 'title',
          right: 'dayGridMonth,timeGridWeek,timeGridDay'
        }}
        events={calendarEvents}
        // Prevent browser context menu on event elements
        eventDidMount={(info) => {
          try {
            // prevent default context menu and open our custom one
            info.el.addEventListener('contextmenu', (e: MouseEvent) => {
              e.preventDefault();
              e.stopPropagation();
              try {
                const evObj = info.event.toPlainObject();
                openMenuForEvent(evObj, e.clientX || 0, e.clientY || 0);
              } catch (ex) {}
            });

            // REMOVED COMPLEX DOM MANIPULATION - Let FullCalendar handle event rendering
            // The CSS styles will handle the visual appearance

          } catch (e) {
            // ignore
          }
        }}
        eventClick={handleEventClick}
        select={handleDateSelect}
        selectable={true}
        editable={true}
        locale="es"
        height="auto"
      />

      {/* Options popover */}
      {anchor && selectedEvent && (
        <div
          style={{ position: 'fixed', left: anchor.x, top: anchor.y, transform: 'translate(6px, 6px)' }}
          className="laborevent-options-menu z-50 w-48 bg-[#F9F1DC] border rounded-md shadow-lg"
        >
          <div className="py-1">
            <button
              onClick={() => { if (selectedEvent) onEventClick?.(selectedEvent); closeMenu(); }}
              className="flex items-center w-full gap-2 px-4 py-2 text-sm text-left text-[#3B4D36] hover:bg-[#E7DCC1] transition-colors"
            >
              <EyeIcon className="w-4 h-4" />
              Ver Perfil
            </button>
            <button
              onClick={() => { /* TODO: open edit modal */ closeMenu(); }}
              className="flex items-center w-full gap-2 px-4 py-2 text-sm text-left text-[#3B4D36] hover:bg-[#E7DCC1] transition-colors"
            >
              <PencilIcon className="w-4 h-4" />
              Editar Información
            </button>
            <div className="border-t border-[#E7DCC1] mx-2 my-1"></div>
            <button
              onClick={handleDeleteClick}
              className="flex items-center w-full gap-2 px-4 py-2 text-sm text-left text-red-600 hover:bg-[#E7DCC1] transition-colors"
            >
              <TrashIcon className="w-4 h-4" />
              Eliminar
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default LaborEventsCalendar;